'use client';
/**
 * ApexVisualizerTool v5 — Collaborative Business Process Map
 *
 * Features:
 *   - Split view: Apex code editor (left) + Business Process flowchart (right)
 *   - Compare mode: Diff two versions of code side-by-side
 *   - Click-to-Rename: Click any node to refine its label (collaborative accuracy)
 *   - @intent comments: Parser reads // @intent labels from code
 *   - Copy Flowchart to Clipboard (as image for Slack/Teams)
 *   - Sanity Check sidebar with anti-pattern detection
 *   - "Generated by Sanity Suite" brand watermark
 *   - PNG/SVG download, LinkedIn share, Sanity Suite CTA
 */
import { useState, useEffect, useRef, useCallback, useId } from 'react';
import { parseApexToMermaid, getApexStats, getNodeMap, SAMPLE_APEX } from '@/lib/apexParser';
import { runSanityChecks } from '@/lib/sanityChecks';

// ─── Mermaid initialisation (client-side only) ───────────────────────────────
let mermaidModule = null;
let mermaidReady = false;

async function ensureMermaid() {
  if (mermaidReady) return mermaidModule;
  const mod = await import('mermaid');
  mermaidModule = mod.default;
  mermaidModule.initialize({
    startOnLoad: false,
    theme: 'dark',
    themeVariables: {
      darkMode: true,
      background: '#0a0a0f',
      primaryColor: '#4f46e5',
      primaryTextColor: '#e2e8f0',
      primaryBorderColor: '#2a2a3a',
      secondaryColor: '#111118',
      tertiaryColor: '#0a0a0f',
      lineColor: '#6366f1',
      textColor: '#e2e8f0',
      mainBkg: '#1a1a24',
      nodeBorder: '#6366f1',
      clusterBkg: '#111118',
      clusterBorder: '#2a2a3a',
      titleColor: '#a5b4fc',
      edgeLabelBackground: '#111118',
    },
    flowchart: {
      htmlLabels: true,
      curve: 'basis',
      rankSpacing: 60,
      nodeSpacing: 40,
      padding: 20,
      wrappingWidth: 200,
    },
    securityLevel: 'loose',
  });
  mermaidReady = true;
  return mermaidModule;
}

// ─── SVG → Canvas helper (for clipboard + PNG download) ─────────────────────
async function svgToCanvas(svgEl, statsObj, scale = 2) {
  const clone = svgEl.cloneNode(true);
  clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
  clone.setAttribute('xmlns:xhtml', 'http://www.w3.org/1999/xhtml');

  // Inline computed styles
  const allOriginal = svgEl.querySelectorAll('*');
  const allCloned = clone.querySelectorAll('*');
  const props = [
    'fill', 'stroke', 'stroke-width', 'color', 'font-size',
    'font-family', 'font-weight', 'opacity', 'transform', 'display',
    'text-anchor', 'dominant-baseline', 'background', 'background-color',
    'border', 'border-radius', 'padding', 'margin', 'line-height',
    'width', 'height', 'overflow', 'white-space', 'word-wrap',
  ];
  for (let i = 0; i < allOriginal.length; i++) {
    const computed = window.getComputedStyle(allOriginal[i]);
    let styleStr = '';
    for (const prop of props) {
      const val = computed.getPropertyValue(prop);
      if (val) styleStr += `${prop}:${val};`;
    }
    if (styleStr) {
      allCloned[i].setAttribute('style',
        (allCloned[i].getAttribute('style') || '') + styleStr
      );
    }
  }

  const serializer = new XMLSerializer();
  const svgStr = serializer.serializeToString(clone);
  const bbox = svgEl.getBoundingClientRect();
  const svgW = bbox.width || 800;
  const svgH = bbox.height || 600;

  // Add room for the watermark bar at bottom
  const watermarkH = 36;
  const canvasW = svgW * scale;
  const canvasH = (svgH + watermarkH) * scale;

  const canvas = document.createElement('canvas');
  canvas.width = canvasW;
  canvas.height = canvasH;
  const ctx = canvas.getContext('2d');

  // Dark background
  ctx.fillStyle = '#0a0a0f';
  ctx.fillRect(0, 0, canvasW, canvasH);

  const svgB64 = btoa(unescape(encodeURIComponent(svgStr)));

  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      ctx.drawImage(img, 0, 0, svgW * scale, svgH * scale);

      // ── Watermark bar ──
      const barY = svgH * scale;
      ctx.fillStyle = '#111118';
      ctx.fillRect(0, barY, canvasW, watermarkH * scale);
      // Line separator
      ctx.strokeStyle = '#2a2a3a';
      ctx.lineWidth = 1 * scale;
      ctx.beginPath();
      ctx.moveTo(0, barY);
      ctx.lineTo(canvasW, barY);
      ctx.stroke();
      // Text
      ctx.fillStyle = '#6366f1';
      ctx.font = `${11 * scale}px -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif`;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(
        'Generated by Sanity Suite  ·  sanity-suite.vercel.app',
        canvasW / 2,
        barY + (watermarkH * scale) / 2
      );

      resolve(canvas);
    };
    img.onerror = () => resolve(null);
    img.src = `data:image/svg+xml;base64,${svgB64}`;
  });
}


// ─── Sub-components ─────────────────────────────────────────────────────────

function StatBadge({ label, value, color = 'accent' }) {
  const colorMap = {
    accent: 'text-accent',
    green: 'text-green-400',
    amber: 'text-amber-400',
    cyan: 'text-cyan-400',
    purple: 'text-purple-400',
    red: 'text-red-400',
  };
  return (
    <div className="flex flex-col items-center rounded-lg border border-border bg-background px-3 py-2 min-w-[70px]">
      <span className={`text-lg font-bold ${colorMap[color] || colorMap.accent}`}>{value}</span>
      <span className="text-[10px] uppercase tracking-wider text-muted">{label}</span>
    </div>
  );
}

/** Severity icon + color */
function SeverityIcon({ severity }) {
  if (severity === 'critical') {
    return (
      <div className="flex-shrink-0 mt-0.5 h-5 w-5 rounded-full bg-red-500/20 flex items-center justify-center">
        <svg className="h-3 w-3 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
        </svg>
      </div>
    );
  }
  if (severity === 'warning') {
    return (
      <div className="flex-shrink-0 mt-0.5 h-5 w-5 rounded-full bg-amber-500/20 flex items-center justify-center">
        <svg className="h-3 w-3 text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
        </svg>
      </div>
    );
  }
  return (
    <div className="flex-shrink-0 mt-0.5 h-5 w-5 rounded-full bg-blue-500/20 flex items-center justify-center">
      <svg className="h-3 w-3 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z" />
      </svg>
    </div>
  );
}


// ─── Sanity Check Sidebar ───────────────────────────────────────────────────

function SanityCheckSidebar({ findings, isVisible }) {
  if (!isVisible || findings.length === 0) return null;

  const critical = findings.filter(f => f.severity === 'critical').length;
  const warnings = findings.filter(f => f.severity === 'warning').length;
  const infos = findings.filter(f => f.severity === 'info').length;

  return (
    <div className="rounded-xl border border-border bg-surface overflow-hidden">
      <div className="flex items-center justify-between border-b border-border/50 px-4 py-3">
        <div className="flex items-center gap-2">
          <svg className="h-4 w-4 text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
          </svg>
          <span className="text-xs font-semibold uppercase tracking-wider text-foreground">
            Sanity Check
          </span>
        </div>
        <div className="flex items-center gap-2 text-[10px] font-medium">
          {critical > 0 && <span className="rounded-full bg-red-500/20 px-2 py-0.5 text-red-400">{critical} Critical</span>}
          {warnings > 0 && <span className="rounded-full bg-amber-500/20 px-2 py-0.5 text-amber-400">{warnings} Warning{warnings > 1 ? 's' : ''}</span>}
          {infos > 0 && <span className="rounded-full bg-blue-500/20 px-2 py-0.5 text-blue-400">{infos} Info</span>}
        </div>
      </div>

      <div className="divide-y divide-border/30">
        {findings.map((f, i) => (
          <div key={i} className="flex gap-3 px-4 py-3">
            <SeverityIcon severity={f.severity} />
            <div className="min-w-0">
              <p className="text-sm font-medium text-foreground">{f.title}</p>
              <p className="mt-0.5 text-xs text-muted leading-relaxed">{f.detail}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Upsell */}
      <div className="border-t border-border/50 bg-accent/5 px-4 py-3">
        <p className="text-xs text-muted leading-relaxed">
          <span className="font-semibold text-accent">Sanity Suite</span> detects 15+ additional anti-patterns including
          governor limit risks, security vulnerabilities, and Flow-Apex conflicts.
        </p>
        <a
          href="https://abhilash38.gumroad.com/l/jdenr?wanted=true"
          target="_blank"
          rel="noopener noreferrer"
          className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-accent hover:text-accent-light transition-colors"
        >
          Unlock Full Analysis
          <svg className="h-3 w-3" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
          </svg>
        </a>
      </div>
    </div>
  );
}


// ─── Code Editor Panel ──────────────────────────────────────────────────────

function CodePanel({ value, onChange, label, placeholder, stats }) {
  const lineCount = (value || '').split('\n').length;
  return (
    <div className="flex flex-col rounded-xl border border-border bg-surface overflow-hidden h-full">
      <div className="flex items-center justify-between border-b border-border/50 px-4 py-2.5">
        <div className="flex items-center gap-2">
          <div className="flex gap-1.5">
            <span className="h-3 w-3 rounded-full bg-red-500/60" />
            <span className="h-3 w-3 rounded-full bg-yellow-500/60" />
            <span className="h-3 w-3 rounded-full bg-green-500/60" />
          </div>
          <span className="ml-2 text-xs font-medium text-muted">
            {stats?.className ? `${stats.className}.cls` : label}
          </span>
        </div>
        <span className="text-[10px] text-muted/60">{lineCount} lines</span>
      </div>
      <div className="relative flex-1">
        <div className="pointer-events-none absolute top-0 left-0 bottom-0 w-12 border-r border-border/30 bg-background/30">
          <div className="p-4 font-mono text-xs leading-[1.7rem] text-muted/30 select-none">
            {Array.from({ length: Math.max(lineCount, 20) }, (_, i) => (
              <div key={i}>{i + 1}</div>
            ))}
          </div>
        </div>
        <textarea
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder}
          spellCheck={false}
          className="h-full w-full resize-none bg-transparent py-4 pr-4 pl-14 font-mono text-sm leading-[1.7rem] text-foreground placeholder-muted/40 focus:outline-none"
          style={{ minHeight: '400px', tabSize: 4 }}
        />
      </div>
    </div>
  );
}


// ─── Flowchart Viewer Panel ─────────────────────────────────────────────────

function FlowchartPanel({ svgContent, error, isRendering, containerRef, onLoadSample, editable = false }) {
  return (
    <div className="flex flex-col rounded-xl border border-border bg-surface overflow-hidden h-full">
      <div className="flex items-center justify-between border-b border-border/50 px-4 py-2.5">
        <div className="flex items-center gap-2">
          <div className="h-2.5 w-2.5 rounded-full bg-accent shadow-sm shadow-accent/40" />
          <span className="text-xs font-medium tracking-wide text-muted uppercase">
            Business Process Map
          </span>
          {isRendering && (
            <span className="ml-2 text-xs text-muted animate-pulse">Rendering...</span>
          )}
        </div>
        {editable && svgContent && (
          <span className="text-[10px] text-muted/60 hidden sm:inline">
            Click any node to rename it
          </span>
        )}
      </div>

      <div className="relative flex-1 overflow-auto" style={{ minHeight: '400px' }}>
        {error ? (
          <div className="m-4 rounded-lg border border-red-500/30 bg-red-500/10 p-4">
            <div className="flex items-start gap-3">
              <svg className="mt-0.5 h-5 w-5 shrink-0 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
              </svg>
              <div>
                <p className="text-sm font-medium text-red-300">Parse Error</p>
                <pre className="mt-1.5 whitespace-pre-wrap text-xs text-red-400/80 font-mono">{error}</pre>
              </div>
            </div>
          </div>
        ) : svgContent ? (
          <div className="flex flex-col h-full">
            <div
              ref={containerRef}
              className={`flex-1 flex justify-center p-6 [&_svg]:max-w-full [&_svg]:h-auto ${editable ? '[&_.node]:cursor-pointer [&_.node:hover]:opacity-80' : ''}`}
              dangerouslySetInnerHTML={{ __html: svgContent }}
            />
            {/* Watermark */}
            <div className="border-t border-border/30 px-4 py-2 text-center">
              <span className="text-[10px] font-medium tracking-wider text-accent/60">
                Generated by Sanity Suite &middot; sanity-suite.vercel.app
              </span>
            </div>
          </div>
        ) : isRendering ? (
          <div className="flex items-center justify-center h-full">
            <div className="h-8 w-8 animate-spin rounded-full border-2 border-border border-t-accent" />
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center h-full text-center px-8">
            <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-surface-light border border-border">
              <svg className="h-8 w-8 text-muted/40" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6A2.25 2.25 0 016 3.75h2.25A2.25 2.25 0 0110.5 6v2.25a2.25 2.25 0 01-2.25 2.25H6a2.25 2.25 0 01-2.25-2.25V6zM3.75 15.75A2.25 2.25 0 016 13.5h2.25a2.25 2.25 0 012.25 2.25V18a2.25 2.25 0 01-2.25 2.25H6A2.25 2.25 0 013.75 18v-2.25zM13.5 6a2.25 2.25 0 012.25-2.25H18A2.25 2.25 0 0120.25 6v2.25A2.25 2.25 0 0118 10.5h-2.25a2.25 2.25 0 01-2.25-2.25V6zM13.5 15.75a2.25 2.25 0 012.25-2.25H18a2.25 2.25 0 012.25 2.25V18A2.25 2.25 0 0118 20.25h-2.25A2.25 2.25 0 0113.5 18v-2.25z" />
              </svg>
            </div>
            <p className="text-sm text-muted">Paste an Apex class to see its business process map.</p>
            <button
              onClick={onLoadSample}
              className="mt-3 text-xs font-medium text-accent hover:text-accent-light transition-colors"
            >
              Or try with a sample class &rarr;
            </button>
          </div>
        )}
      </div>
    </div>
  );
}


// ─── Main component ─────────────────────────────────────────────────────────

export default function ApexVisualizerTool() {
  // ── Mode: 'single' or 'compare' ──
  const [mode, setMode] = useState('single');

  // ── Single mode state ──
  const [apexCode, setApexCode] = useState('');
  const [mermaidCode, setMermaidCode] = useState('');
  const [svgContent, setSvgContent] = useState('');
  const [stats, setStats] = useState(null);
  const [findings, setFindings] = useState([]);
  const [error, setError] = useState(null);
  const [isRendering, setIsRendering] = useState(false);
  const [copiedChart, setCopiedChart] = useState(false);
  const [copiedMermaid, setCopiedMermaid] = useState(false);

  // ── Node rename state (collaborative refinement) ──
  const [nodeOverrides, setNodeOverrides] = useState({});
  const [customSteps, setCustomSteps] = useState([]); // [{ label, type }]
  const [renameNode, setRenameNode] = useState(null); // { id, label }
  const [renameValue, setRenameValue] = useState('');
  const [nodeMap, setNodeMap] = useState({});
  const [showAddStep, setShowAddStep] = useState(false);
  const [newStepLabel, setNewStepLabel] = useState('');

  // ── Compare mode state ──
  const [compareA, setCompareA] = useState('');
  const [compareB, setCompareB] = useState('');
  const [svgA, setSvgA] = useState('');
  const [svgB, setSvgB] = useState('');
  const [errorA, setErrorA] = useState(null);
  const [errorB, setErrorB] = useState(null);
  const [renderingA, setRenderingA] = useState(false);
  const [renderingB, setRenderingB] = useState(false);

  const containerRef = useRef(null);
  const containerARef = useRef(null);
  const containerBRef = useRef(null);
  const renderIdRef = useRef(0);
  const renderARef = useRef(0);
  const renderBRef = useRef(0);
  const uniqueId = useId().replace(/:/g, '_');

  // ── Render helper (reusable for single + compare) ──
  const renderMermaid = useCallback(async (code, graphPrefix, renderId, overrides = {}, extras = []) => {
    const mermaid_output = parseApexToMermaid(code, overrides, extras);
    if (!mermaid_output) return { mermaid: '', svg: '', error: 'No Apex constructs found.' };

    try {
      const mermaid = await ensureMermaid();
      const graphId = `${graphPrefix}_${uniqueId}_${renderId}`;
      const { svg } = await mermaid.render(graphId, mermaid_output);
      return { mermaid: mermaid_output, svg, error: null };
    } catch (err) {
      return { mermaid: mermaid_output, svg: '', error: err?.message || 'Rendering failed' };
    }
  }, [uniqueId]);

  // ── Single mode render (debounced) ──
  useEffect(() => {
    if (mode !== 'single') return;
    const trimmed = (apexCode || '').trim();
    if (!trimmed) {
      setMermaidCode(''); setSvgContent(''); setStats(null); setFindings([]); setError(null); setNodeMap({});
      return;
    }

    const timeout = setTimeout(async () => {
      setStats(getApexStats(trimmed));
      setFindings(runSanityChecks(trimmed));
      setNodeMap(getNodeMap(trimmed, nodeOverrides));
      setIsRendering(true);
      setError(null);
      const thisRender = ++renderIdRef.current;

      const result = await renderMermaid(trimmed, 'viz', thisRender, nodeOverrides, customSteps);
      if (thisRender === renderIdRef.current) {
        setMermaidCode(result.mermaid);
        setSvgContent(result.svg);
        setError(result.error);
        setIsRendering(false);
      }
    }, 400);
    return () => clearTimeout(timeout);
  }, [apexCode, mode, nodeOverrides, customSteps, renderMermaid]);

  // ── Compare mode render A (debounced) ──
  useEffect(() => {
    if (mode !== 'compare') return;
    const trimmed = (compareA || '').trim();
    if (!trimmed) { setSvgA(''); setErrorA(null); return; }

    const timeout = setTimeout(async () => {
      setRenderingA(true);
      const thisRender = ++renderARef.current;
      const result = await renderMermaid(trimmed, 'cmpA', thisRender);
      if (thisRender === renderARef.current) {
        setSvgA(result.svg); setErrorA(result.error); setRenderingA(false);
      }
    }, 400);
    return () => clearTimeout(timeout);
  }, [compareA, mode, renderMermaid]);

  // ── Compare mode render B (debounced) ──
  useEffect(() => {
    if (mode !== 'compare') return;
    const trimmed = (compareB || '').trim();
    if (!trimmed) { setSvgB(''); setErrorB(null); return; }

    const timeout = setTimeout(async () => {
      setRenderingB(true);
      const thisRender = ++renderBRef.current;
      const result = await renderMermaid(trimmed, 'cmpB', thisRender);
      if (thisRender === renderBRef.current) {
        setSvgB(result.svg); setErrorB(result.error); setRenderingB(false);
      }
    }, 400);
    return () => clearTimeout(timeout);
  }, [compareB, mode, renderMermaid]);

  // ── Node click handler (for click-to-rename) ──
  useEffect(() => {
    if (!svgContent || mode !== 'single') return;
    const el = containerRef.current;
    if (!el) return;

    function handleNodeClick(e) {
      // Find the closest Mermaid node group
      const nodeEl = e.target.closest('[id^="flowchart-n"]') || e.target.closest('.node');
      if (!nodeEl) return;

      // Extract node ID from the element ID (e.g., "flowchart-n2-123" → "n2")
      const idMatch = nodeEl.id?.match(/(n\d+)/);
      if (!idMatch) return;
      const nId = idMatch[1];

      // Look up in node map
      const nodeInfo = nodeMap[nId];
      if (!nodeInfo || nodeInfo.editable === false) return;

      // Open rename modal
      setRenameNode({ id: nId, label: nodeInfo.label });
      setRenameValue(nodeInfo.label);
    }

    el.addEventListener('click', handleNodeClick);
    return () => el.removeEventListener('click', handleNodeClick);
  }, [svgContent, nodeMap, mode]);

  function handleRenameSubmit() {
    if (!renameNode || !renameValue.trim()) return;
    setNodeOverrides(prev => ({ ...prev, [renameNode.id]: renameValue.trim() }));
    setRenameNode(null);
    setRenameValue('');
  }

  function handleResetOverrides() {
    setNodeOverrides({});
    setCustomSteps([]);
  }

  function handleAddStep() {
    if (!newStepLabel.trim()) return;
    setCustomSteps(prev => [...prev, { label: newStepLabel.trim(), type: 'custom' }]);
    setNewStepLabel('');
    setShowAddStep(false);
  }

  function handleRemoveCustomStep(index) {
    setCustomSteps(prev => prev.filter((_, i) => i !== index));
  }

  // ── Actions ──
  function handleLoadSample() { setApexCode(SAMPLE_APEX); setNodeOverrides({}); setCustomSteps([]); }
  function handleClear() { setApexCode(''); setNodeOverrides({}); setCustomSteps([]); }

  function handleSwitchMode(newMode) {
    if (newMode === 'compare' && mode === 'single') {
      setCompareA(apexCode);
      setCompareB('');
    } else if (newMode === 'single' && mode === 'compare') {
      setApexCode(compareA || compareB);
    }
    setMode(newMode);
  }

  function handleDownloadSvg() {
    if (!svgContent) return;
    const blob = new Blob([svgContent], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${stats?.className || 'apex'}-flowchart.svg`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  async function handleDownloadPng() {
    const el = containerRef.current;
    if (!el) return;
    const svgEl = el.querySelector('svg');
    if (!svgEl) return;

    const canvas = await svgToCanvas(svgEl, stats);
    if (!canvas) {
      // Fallback: open SVG in new tab
      const blob = new Blob([svgContent], { type: 'image/svg+xml' });
      window.open(URL.createObjectURL(blob), '_blank');
      return;
    }

    canvas.toBlob((blob) => {
      if (blob) {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${stats?.className || 'apex'}-flowchart.png`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      }
    }, 'image/png');
  }

  async function handleCopyFlowchart() {
    const el = containerRef.current;
    if (!el) return;
    const svgEl = el.querySelector('svg');
    if (!svgEl) return;

    const canvas = await svgToCanvas(svgEl, stats);
    if (!canvas) return;

    try {
      const blob = await new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
      if (blob) {
        await navigator.clipboard.write([
          new ClipboardItem({ 'image/png': blob })
        ]);
        setCopiedChart(true);
        setTimeout(() => setCopiedChart(false), 2500);
      }
    } catch {
      // Fallback: copy mermaid text if image clipboard not supported
      try {
        await navigator.clipboard.writeText(mermaidCode);
        setCopiedChart(true);
        setTimeout(() => setCopiedChart(false), 2500);
      } catch { /* silent */ }
    }
  }

  function handleCopyMermaid() {
    if (!mermaidCode) return;
    navigator.clipboard.writeText(mermaidCode).then(() => {
      setCopiedMermaid(true);
      setTimeout(() => setCopiedMermaid(false), 2000);
    });
  }

  function handleShareLinkedIn() {
    const text = encodeURIComponent(
      `I just visualized my Apex class as a Business Process Map — no login, no server, 100% in-browser.\n\nPaste any Apex class and see the story of what your code does, instantly.\n\nTry it: https://sanity-suite.vercel.app/tools/apex-visualizer\n\n#Salesforce #ApexDev #SalesforceDeveloper #SanitySuite`
    );
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent('https://sanity-suite.vercel.app/tools/apex-visualizer')}&summary=${text}`, '_blank');
  }

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* ── Hero ── */}
      <section className="relative overflow-hidden border-b border-border pt-28 pb-12 md:pt-32 md:pb-16">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute top-0 left-1/3 h-72 w-72 rounded-full bg-accent/10 blur-3xl" />
          <div className="absolute top-10 right-1/4 h-56 w-56 rounded-full bg-purple-500/10 blur-3xl" />
        </div>
        <div className="relative mx-auto max-w-7xl px-6 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-surface px-4 py-1.5">
            <span className="h-2 w-2 rounded-full bg-green-400 animate-pulse" />
            <span className="text-xs font-medium text-muted">Free Tool — No Login Required</span>
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">
            Apex <span className="gradient-text">Visualizer</span>
          </h1>
          <p className="mx-auto mt-3 max-w-xl text-base text-muted">
            Paste any Apex class and see its business process map — what your code
            actually <em>does</em>, not how it&apos;s written. 100% client-side.
          </p>
        </div>
      </section>

      {/* ── Toolbar ── */}
      <div className="sticky top-16 z-30 border-b border-border bg-background/90 backdrop-blur-md">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-2.5">
          <div className="flex items-center gap-2">
            {/* Mode toggle */}
            <div className="flex rounded-lg border border-border overflow-hidden">
              <button
                onClick={() => handleSwitchMode('single')}
                className={`px-3 py-1.5 text-xs font-medium transition-colors ${mode === 'single' ? 'bg-accent text-white' : 'text-muted hover:text-foreground'}`}
              >
                Visualize
              </button>
              <button
                onClick={() => handleSwitchMode('compare')}
                className={`px-3 py-1.5 text-xs font-medium transition-colors ${mode === 'compare' ? 'bg-accent text-white' : 'text-muted hover:text-foreground'}`}
              >
                Compare
              </button>
            </div>

            <div className="mx-1 h-4 w-px bg-border" />

            {mode === 'single' && (
              <>
                <button
                  onClick={handleLoadSample}
                  className="rounded-lg border border-border px-3 py-1.5 text-xs font-medium text-muted transition-colors hover:border-accent/40 hover:text-foreground"
                >
                  Load Sample
                </button>
                <button
                  onClick={handleClear}
                  className="rounded-lg border border-border px-3 py-1.5 text-xs font-medium text-muted transition-colors hover:border-red-500/40 hover:text-red-400"
                >
                  Clear
                </button>
                {svgContent && (
                  <button
                    onClick={() => setShowAddStep(true)}
                    className="rounded-lg border border-accent/30 px-3 py-1.5 text-xs font-medium text-accent transition-colors hover:bg-accent/10"
                    title="Add a custom step to the flowchart"
                  >
                    + Add Step
                  </button>
                )}
                {(Object.keys(nodeOverrides).length > 0 || customSteps.length > 0) && (
                  <button
                    onClick={handleResetOverrides}
                    className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-1.5 text-xs font-medium text-amber-400 transition-colors hover:bg-amber-500/20"
                    title="Reset all customizations"
                  >
                    Reset ({Object.keys(nodeOverrides).length + customSteps.length})
                  </button>
                )}
                {stats && (
                  <span className="ml-2 hidden text-xs text-muted sm:inline">
                    {stats.className} &middot; {stats.codeLines} lines &middot; {stats.methodCount} method{stats.methodCount !== 1 ? 's' : ''}
                    {stats.intentCount > 0 && <> &middot; <span className="text-green-400">{stats.intentCount} @intent</span></>}
                  </span>
                )}
              </>
            )}
          </div>

          {mode === 'single' && (
            <div className="flex items-center gap-1.5">
              {/* Copy Flowchart (image) */}
              <button
                onClick={handleCopyFlowchart}
                disabled={!svgContent}
                className="flex items-center gap-1.5 rounded-lg border border-accent/30 bg-accent/10 px-3 py-1.5 text-xs font-medium text-accent transition-colors hover:bg-accent/20 disabled:opacity-30 disabled:cursor-not-allowed"
                title="Copy flowchart image to clipboard"
              >
                {copiedChart ? (
                  <svg className="h-3.5 w-3.5 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                ) : (
                  <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.666 3.888A2.25 2.25 0 0013.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 01-.75.75H9.75a.75.75 0 01-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 01-2.25 2.25H6.75A2.25 2.25 0 014.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 011.927-.184" />
                  </svg>
                )}
                {copiedChart ? 'Copied!' : 'Copy Chart'}
              </button>

              <button
                onClick={handleCopyMermaid}
                disabled={!mermaidCode}
                className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium text-muted transition-colors hover:bg-surface hover:text-foreground disabled:opacity-30 disabled:cursor-not-allowed"
                title="Copy Mermaid code"
              >
                {copiedMermaid ? (
                  <svg className="h-3.5 w-3.5 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                  </svg>
                ) : (
                  <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
                  </svg>
                )}
                {copiedMermaid ? 'Copied' : 'Mermaid'}
              </button>

              <button
                onClick={handleDownloadSvg}
                disabled={!svgContent}
                className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium text-muted transition-colors hover:bg-surface hover:text-foreground disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                </svg>
                SVG
              </button>
              <button
                onClick={handleDownloadPng}
                disabled={!svgContent}
                className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium text-muted transition-colors hover:bg-surface hover:text-foreground disabled:opacity-30 disabled:cursor-not-allowed"
              >
                <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                </svg>
                PNG
              </button>
              <div className="mx-1 h-4 w-px bg-border" />
              <button
                onClick={handleShareLinkedIn}
                className="flex items-center gap-1.5 rounded-lg bg-[#0A66C2] px-3 py-1.5 text-xs font-medium text-white transition-opacity hover:opacity-90"
              >
                <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
                </svg>
                Share
              </button>
            </div>
          )}
        </div>
      </div>

      {/* ── Content Area ── */}
      <div className="mx-auto max-w-7xl px-6 py-6">

        {/* ═══ SINGLE MODE ═══ */}
        {mode === 'single' && (
          <>
            <div className="grid gap-4 lg:grid-cols-2" style={{ minHeight: '65vh' }}>
              {/* Left: Code Editor */}
              <CodePanel
                value={apexCode}
                onChange={setApexCode}
                label="Apex Class"
                placeholder={"Paste your Apex class here...\n\nOr click 'Load Sample' to see it in action."}
                stats={stats}
              />

              {/* Right: Flowchart */}
              <FlowchartPanel
                svgContent={svgContent}
                error={error}
                isRendering={isRendering}
                containerRef={containerRef}
                onLoadSample={handleLoadSample}
                editable={true}
              />
            </div>

            {/* Stats + Sanity Checks row */}
            {stats && (
              <div className="mt-4 grid gap-4 lg:grid-cols-3">
                {/* Stats bar */}
                <div className="lg:col-span-2 rounded-xl border border-border bg-surface p-4">
                  <div className="flex flex-wrap items-center justify-center gap-3">
                    <StatBadge label="Lines" value={stats.codeLines} color="accent" />
                    <StatBadge label="Methods" value={stats.methodCount} color="green" />
                    <StatBadge label="SOQL" value={stats.soqlCount} color="cyan" />
                    <StatBadge label="DML" value={stats.dmlCount} color="purple" />
                    <StatBadge label="Branches" value={stats.ifCount} color="amber" />
                    <StatBadge label="Loops" value={stats.loopCount} color="purple" />
                    {stats.eventCount > 0 && (
                      <StatBadge label="Events" value={stats.eventCount} color="accent" />
                    )}
                    <div className="ml-2 flex flex-col items-center rounded-lg border border-accent/30 bg-accent/10 px-4 py-2">
                      <span className="text-lg font-bold text-accent">{stats.complexity}</span>
                      <span className="text-[10px] uppercase tracking-wider text-accent/80">Complexity</span>
                    </div>
                  </div>
                </div>

                {/* Sanity Check sidebar */}
                <SanityCheckSidebar findings={findings} isVisible={findings.length > 0} />

                {/* If no findings, show a clean bill of health */}
                {findings.length === 0 && (
                  <div className="rounded-xl border border-border bg-surface p-4 flex flex-col items-center justify-center text-center">
                    <div className="h-10 w-10 rounded-full bg-green-500/10 flex items-center justify-center mb-2">
                      <svg className="h-5 w-5 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                    <p className="text-xs font-medium text-green-400">No issues detected</p>
                    <p className="mt-1 text-[10px] text-muted">Basic sanity checks passed</p>
                  </div>
                )}
              </div>
            )}
          </>
        )}

        {/* ═══ COMPARE MODE ═══ */}
        {mode === 'compare' && (
          <div className="space-y-4">
            <div className="rounded-xl border border-accent/20 bg-accent/5 px-4 py-3 text-center">
              <p className="text-sm text-muted">
                <span className="font-semibold text-accent">Compare Mode</span> — Paste two versions of your Apex class to see how the business logic changed.
              </p>
            </div>

            {/* Top row: two code editors */}
            <div className="grid gap-4 lg:grid-cols-2" style={{ minHeight: '300px' }}>
              <CodePanel
                value={compareA}
                onChange={setCompareA}
                label="Version A (Before)"
                placeholder="Paste the BEFORE version here..."
                stats={null}
              />
              <CodePanel
                value={compareB}
                onChange={setCompareB}
                label="Version B (After)"
                placeholder="Paste the AFTER version here..."
                stats={null}
              />
            </div>

            {/* Bottom row: two flowcharts */}
            <div className="grid gap-4 lg:grid-cols-2" style={{ minHeight: '350px' }}>
              <FlowchartPanel
                svgContent={svgA}
                error={errorA}
                isRendering={renderingA}
                containerRef={containerARef}
                onLoadSample={() => setCompareA(SAMPLE_APEX)}
              />
              <FlowchartPanel
                svgContent={svgB}
                error={errorB}
                isRendering={renderingB}
                containerRef={containerBRef}
                onLoadSample={() => setCompareB(SAMPLE_APEX)}
              />
            </div>
          </div>
        )}
      </div>

      {/* ── CTA Banner ── */}
      <section className="border-t border-border py-16 md:py-20">
        <div className="mx-auto max-w-4xl px-6">
          <div className="relative overflow-hidden rounded-2xl border border-border bg-surface p-10 text-center md:p-14">
            <div className="pointer-events-none absolute inset-0">
              <div className="absolute -bottom-16 left-1/2 h-64 w-64 -translate-x-1/2 rounded-full bg-accent/15 blur-3xl" />
            </div>
            <div className="relative">
              <p className="text-sm font-semibold uppercase tracking-widest text-accent">
                Go Deeper
              </p>
              <h2 className="mt-3 text-2xl font-bold tracking-tight sm:text-3xl">
                Want Full Flow Governance &amp;{' '}
                <span className="gradient-text">Security Audits</span>?
              </h2>
              <p className="mx-auto mt-4 max-w-lg text-sm text-muted leading-relaxed">
                The Sanity Suite LWC runs inside your Salesforce org — audit Flow XML,
                patch Permission Sets, extract deterministic logic hashes, and score
                your Flow health. All client-side, zero data exposure.
              </p>
              <div className="mt-8 flex flex-col items-center gap-3 sm:flex-row sm:justify-center">
                <a
                  href="https://abhilash38.gumroad.com/l/jdenr?wanted=true"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="rounded-lg bg-accent px-8 py-3.5 text-sm font-semibold text-white shadow-lg shadow-accent/25 transition-all hover:bg-accent-light hover:shadow-accent/40"
                >
                  Get Sanity Suite — $29
                </a>
                <a
                  href="/"
                  className="rounded-lg border border-border px-8 py-3.5 text-sm font-semibold text-foreground transition-colors hover:border-accent/40 hover:bg-surface-light"
                >
                  Learn More
                </a>
              </div>
              <p className="mt-4 text-xs text-muted">
                Installs in under 5 minutes. No external dependencies.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Add Step Modal ── */}
      {showAddStep && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="mx-4 w-full max-w-md rounded-2xl border border-border bg-surface p-6 shadow-2xl">
            <h3 className="text-sm font-semibold text-foreground">Add Custom Step</h3>
            <p className="mt-1 text-xs text-muted">
              Add a business process step that isn&apos;t detected automatically. It will appear at the end of the flow.
            </p>
            <input
              type="text"
              value={newStepLabel}
              onChange={(e) => setNewStepLabel(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') handleAddStep(); if (e.key === 'Escape') setShowAddStep(false); }}
              className="mt-3 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm text-foreground placeholder-muted/40 focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
              placeholder="e.g., Send Confirmation Email to Customer"
              autoFocus
            />
            {customSteps.length > 0 && (
              <div className="mt-3 space-y-1">
                <p className="text-[10px] font-medium uppercase tracking-wider text-muted">Current custom steps:</p>
                {customSteps.map((step, i) => (
                  <div key={i} className="flex items-center justify-between rounded-lg border border-border/50 bg-background/50 px-3 py-1.5">
                    <span className="text-xs text-foreground">{step.label}</span>
                    <button
                      onClick={() => handleRemoveCustomStep(i)}
                      className="text-xs text-red-400 hover:text-red-300"
                    >
                      Remove
                    </button>
                  </div>
                ))}
              </div>
            )}
            <div className="mt-4 flex items-center justify-end gap-2">
              <button
                onClick={() => { setShowAddStep(false); setNewStepLabel(''); }}
                className="rounded-lg border border-border px-4 py-2 text-xs font-medium text-muted transition-colors hover:text-foreground"
              >
                {customSteps.length > 0 ? 'Done' : 'Cancel'}
              </button>
              <button
                onClick={handleAddStep}
                disabled={!newStepLabel.trim()}
                className="rounded-lg bg-accent px-4 py-2 text-xs font-semibold text-white transition-opacity hover:opacity-90 disabled:opacity-30"
              >
                Add Step
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Rename Modal ── */}
      {renameNode && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm">
          <div className="mx-4 w-full max-w-md rounded-2xl border border-border bg-surface p-6 shadow-2xl">
            <h3 className="text-sm font-semibold text-foreground">Rename Node</h3>
            <p className="mt-1 text-xs text-muted">
              Refine this label to match your business context. Your changes persist until you reset.
            </p>
            <input
              type="text"
              value={renameValue}
              onChange={(e) => setRenameValue(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') handleRenameSubmit(); if (e.key === 'Escape') setRenameNode(null); }}
              className="mt-3 w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm text-foreground placeholder-muted/40 focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
              placeholder="e.g., Create Provisioning Case for the Order"
              autoFocus
            />
            <div className="mt-4 flex items-center justify-between">
              <button
                onClick={() => {
                  // Remove this node's override (hide node)
                  setNodeOverrides(prev => {
                    const next = { ...prev };
                    next[renameNode.id] = '__HIDDEN__';
                    return next;
                  });
                  setRenameNode(null);
                }}
                className="text-xs font-medium text-red-400 hover:text-red-300 transition-colors"
                title="Hide this node from the flowchart"
              >
                Hide Node
              </button>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setRenameNode(null)}
                  className="rounded-lg border border-border px-4 py-2 text-xs font-medium text-muted transition-colors hover:text-foreground"
                >
                  Cancel
                </button>
                <button
                  onClick={handleRenameSubmit}
                  className="rounded-lg bg-accent px-4 py-2 text-xs font-semibold text-white transition-opacity hover:opacity-90"
                >
                  Save
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
